# Generated by Django 2.0.1 on 2018-08-16 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128, unique=True, verbose_name='堡垒机用户组名')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '堡垒机用户组',
                'verbose_name_plural': '堡垒机用户组',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=128, unique=True, verbose_name='远程主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('port', models.SmallIntegerField(default=22, verbose_name='端口')),
                ('release', models.CharField(default='CentOS', max_length=256, verbose_name='发行版本')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '远程主机',
                'verbose_name_plural': '远程主机',
            },
        ),
        migrations.CreateModel(
            name='RemoteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_user_name', models.CharField(max_length=128, verbose_name='远程主机用户名')),
                ('password', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': '远程主机用户',
                'verbose_name_plural': '远程主机用户',
            },
        ),
        migrations.CreateModel(
            name='RemoteUserBindHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fort.Host')),
                ('remote_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fort.RemoteUser')),
            ],
            options={
                'verbose_name': '用户绑定主机',
                'verbose_name_plural': '用户绑定主机',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='普通用户', max_length=128, verbose_name='用户类型')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否可以登录堡垒机')),
                ('groups', models.ManyToManyField(blank=True, to='fort.Group', verbose_name='所属堡垒机用户组')),
                ('remote_user_bind_hosts', models.ManyToManyField(blank=True, to='fort.RemoteUserBindHost', verbose_name='堡垒机用户关联的远程用户')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '堡垒机用户',
                'verbose_name_plural': '堡垒机用户',
            },
        ),
        migrations.AlterUniqueTogether(
            name='remoteuser',
            unique_together={('remote_user_name', 'password')},
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('ip', 'port')},
        ),
        migrations.AddField(
            model_name='group',
            name='remote_user_bind_hosts',
            field=models.ManyToManyField(blank=True, to='fort.RemoteUserBindHost', verbose_name='组内关联的远程用户'),
        ),
        migrations.AlterUniqueTogether(
            name='remoteuserbindhost',
            unique_together={('host', 'remote_user')},
        ),
    ]
