# Generated by Django 2.0.1 on 2018-08-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(default=22, verbose_name='端口'),
        ),
    ]
